@startuml
'https://plantuml.com/class-diagram

Class App {
- main()
- start()
- viewHome()
}

class itemProperties {
    + itemDescription: SimpleStringProperty
    + dueDate: SimpleStringProperty
    + completed: SimpleStringProperty

    - itemProperties(itemDescription, dueDate)
    - getItemDescription()
    - setItemDescription(itemDescription)
    - getDueDate()
    - setDueDate(dueDate)
    - getCompleted()
    - setCompleted(completed)
}

class listsController {
+ location: URL
+ resources: ResourceBundle
+ actionEvent: ActionEvent

- addItems(ActionEvent)
- addList(ActionEvent)
- deleteList(ActionEvent)
- saveList(ActionEvent)
- loadList(ActionEvent)
- fileSaver()
- fileLoader()
- Initialize(location, resources)
}

class toDoList {
    + listName: SimpleStringProperty
    + itemPropertiesObservableList: itemObservableList

    - toDoList(listName)
    - getListName()
    - setListName(listName)
    - getItemObservableList()
    - setItemObservableList(itemObservableList)
}

class toDoListController {
    - addItem(ActionEvent)
    - backToList(ActionEvent)
    - checkComplete(ActionEvent)
    - filterItems(ActionEvent)
    - removeItem(ActionEvent)
    - showCompletedFilter(ActionEvent)
    - showUncompletedFilter(ActionEvent)
    - sortByDueDateFilter(ActionEvent)
    - Initialize(location, resources)
}


@enduml