@startuml
'https://plantuml.com/class-diagram

Class App {
+ main()
+ start()
- viewToDoList()
}

class itemProperties {
    - itemDescription: SimpleStringProperty
    - dueDate: SimpleStringProperty
    - completed: SimpleBooleanProperty

    + itemProperties(itemDescription, dueDate)
    + getItemDescription()
    + setItemDescription(itemDescription)
    + getDueDate()
    + setDueDate(dueDate)
    + getCompleted()
    + setCompleted(completed)
    + itemDescriptionProperty(itemDescription)
    + dueDateProperty(dueDate)
    + completedProperty(completed)
}

class toDoListController {
    - completed: SimpleBooleanProperty
    - toDoListCompleted: ObservableList<itemProperties>
    - toDoListUncompleted: ObservableList<itemProperties>
    + toDoList: ObservableList<itemProperties>
    + location: URL
    + resources: ResourceBundle
    + actionEvent: ActionEvent

    - filteredList: FilteredList<itemProperties>(toDoList)
    + addItem(ActionEvent)
    + formatDueDate(Date Picker)
    + clearList(ActionEvent)
    + removeItem(ActionEvent)
    + showCompletedFilter(ActionEvent)
    + showEntireList(ActionEvent)
    + showUncompletedFilter(ActionEvent)
    + sortByDueDateAscendingFilter(ActionEvent)
    + sortByDueDateDescendingFilter(ActionEvent)
    + saveList(ActionEvent)
    + loadList(ActionEvent)
    + Initialize(location, resources)

}

class toDoListController {



}


@enduml